### ISSUE TITLE
ValueError: torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU

### ISSUE THREAD

**Issue by lemoneder** [RedRayz/Kohya_lora_param_gui#18]
簡易設定、通常設定共に同様のエラーが発生しました。C直下以外にデスクトップ等も試してみましたが同様でした。

C:\train\sd-scripts\venv\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\train\sd-scripts\venv\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.0+cu121 with CUDA 1201 (you have 2.1.0+cpu)
    Python  3.10.11 (you have 3.10.11)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
C:\train\sd-scripts\venv\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\train\sd-scripts\venv\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
prepare tokenizer
Using DreamBooth method.
prepare images.
found directory C:\train\training\80_doskoinpo contains 80 image files
6400 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 2
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 320
  max_bucket_reso: 1024
  bucket_reso_steps: 64
  bucket_no_upscale: False

  [Subset 0 of Dataset 0]
    image_dir: "C:\train\training\80_doskoinpo"
    image_count: 80
    num_repeats: 80
    shuffle_caption: True
    keep_tokens: 1
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: doskoinpo
    caption_extension: .txt

[Dataset 0]
loading image sizes.
100%|███████████████████████████████████████████████████████████████████████████████| 80/80 [00:00<00:00, 16053.98it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (384, 640), count: 240
bucket 1: resolution (448, 576), count: 800
bucket 2: resolution (512, 512), count: 320
bucket 3: resolution (576, 448), count: 4960
bucket 4: resolution (640, 384), count: 80
mean ar error (without repeats): 0.04679608033441236
preparing accelerator
loading model for process 0/1
load StableDiffusion checkpoint: C:\sd2\webui\models\Stable-diffusion\koji_v21.safetensors
UNet2DConditionModel: 64, 8, 768, False, False
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
Enable xformers for U-Net
Traceback (most recent call last):
  File "C:\train\sd-scripts\train_network.py", line 1012, in <module>
    trainer.train(args)
  File "C:\train\sd-scripts\train_network.py", line 236, in train
    vae.set_use_memory_efficient_attention_xformers(args.xformers)
  File "C:\train\sd-scripts\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 251, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "C:\train\sd-scripts\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\train\sd-scripts\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\train\sd-scripts\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\train\sd-scripts\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 244, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "C:\train\sd-scripts\venv\lib\site-packages\diffusers\models\attention_processor.py", line 203, in set_use_memory_efficient_attention_xformers
    raise ValueError(
ValueError: torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU
Traceback (most recent call last):
  File "C:\Users\lemon\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\lemon\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\train\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\train\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\train\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "C:\train\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\train\\sd-scripts\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path', 'C:\\sd2\\webui\\models\\Stable-diffusion\\koji_v21.safetensors', '--train_data_dir', 'C:\\train\\training', '--output_dir', 'C:\\train\\output', '--network_module', 'networks.lora', '--xformers', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '1', '--enable_bucket', '--save_model_as', 'safetensors', '--lr_scheduler_num_cycles', '4', '--mixed_precision', 'fp16', '--learning_rate', '0.0001', '--resolution', '512', '--train_batch_size', '2', '--max_train_epochs', '30', '--network_dim', '64', '--network_alpha', '16', '--shuffle_caption', '--keep_tokens', '1', '--save_every_n_epochs', '10', '--optimizer_type', 'Lion', '--output_name', 'doskoinpo', '--clip_skip', '2', '--save_precision', 'fp16', '--lr_scheduler', 'cosine_with_restarts', '--min_bucket_reso', '320', '--max_bucket_reso', '1024', '--caption_extension', '.txt', '--seed', '42']' returned non-zero exit status 1.

(venv) C:\train\sd-scripts>

**Comment by RedRayz** [comment]
ご報告ありがとうございます。不具合を修正したものをリリースしました。
GUIの更新後にユーティリティからvenvを再生成するとエラーは解消します。

どうやらtorch側のバージョンアップでxformers非互換のパッケージがインストールされてしまうことが原因だったため、対応バージョンをインストールするように変更しました。
