### ISSUE TITLE
loraの学習がハジマリマセン

### ISSUE THREAD

**Issue by Zakutu** [RedRayz/Kohya_lora_param_gui#42]
Traceback (most recent call last):
  File "C:\Lora-make\sd-scripts\sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "C:\Lora-make\sd-scripts\train_network.py", line 804, in train
    for step, batch in enumerate(train_dataloader):
  File "C:\Lora-make\sd-scripts\venv\lib\site-packages\accelerate\data_loader.py", line 448, in __iter__
    current_batch = next(dataloader_iter)
  File "C:\Lora-make\sd-scripts\venv\lib\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
  File "C:\Lora-make\sd-scripts\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "C:\Lora-make\sd-scripts\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "C:\Lora-make\sd-scripts\venv\lib\site-packages\torch\_utils.py", line 694, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Lora-make\sd-scripts\venv\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Lora-make\sd-scripts\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Lora-make\sd-scripts\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Lora-make\sd-scripts\venv\lib\site-packages\torch\utils\data\dataset.py", line 302, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "C:\Lora-make\sd-scripts\library\train_util.py", line 1341, in __getitem__
    example["latents"] = torch.stack(latents_list) if latents_list[0] is not None else None
RuntimeError: stack expects each tensor to be equal size, but got [4, 96, 168] at entry 0 and [4, 104, 152] at entry 1

steps:   0%|                                                                                  | 0/1540 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\eggof\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\eggof\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Lora-make\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Lora-make\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Lora-make\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\Lora-make\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Lora-make\\sd-scripts\\venv\\Scripts\\python.exe', 'sdxl_train_network.py', '--pretrained_model_name_or_path', 'D:\\model\\SDXL\\animagineXLV31_v31.safetensors', '--train_data_dir', 'C:\\Lora-make\\image\\train', '--output_dir', 'C:\\Lora-make', '--network_module', 'networks.lora', '--xformers', '--gradient_checkpointing', '--persistent_data_loader_workers', '--cache_latents', '--cache_latents_to_disk', '--max_data_loader_n_workers', '1', '--enable_bucket', '--save_model_as', 'safetensors', '--lr_scheduler_num_cycles', '4', '--mixed_precision', 'fp16', '--learning_rate', '1', '--resolution', '1024', '--train_batch_size', '2', '--max_train_epochs', '14', '--network_dim', '8', '--network_alpha', '2', '--shuffle_caption', '--keep_tokens', '1', '--optimizer_type', 'prodigy', '--optimizer_args', 'betas=0.9,0.99', 'eps=1e-08', 'weight_decay=0', 'd0=1e-06', 'decouple=False', 'd_coef=1', 'use_bias_correction=False', 'safeguard_warmup=True', '--lr_warmup_steps', '100', '--output_name', 'SDXL_template', '--save_precision', 'fp16', '--lr_scheduler', 'cosine_with_restarts', '--min_bucket_reso', '512', '--max_bucket_reso', '2048', '--caption_extension', '.txt', '--seed', '42', '--fp8_base', '--loss_type', 'l2', '--huber_schedule', 'snr']' returned non-zero exit status 1.

**Comment by RedRayz** [comment]
これはGUIの不具合ではありません。
データセット内の同名の拡張子の異なるファイル(例:aaa.jpgとaaa.png)の競合の可能性があります。名前が重複しているものとすべてのnpzファイルを削除してください。
https://github.com/kohya-ss/sd-scripts/issues/958#issuecomment-1831853682
